apiVersion: apps/v1
kind: Deployment

metadata:
  name: vehicle-sales-api

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: vehicle-sales-api

  template:
    metadata:
      labels:
        app: vehicle-sales-api

    spec:
      containers:

        - name: vehicle-sales-api

          image: gabriellimadasilva/vehicle-sales-api:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production

            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: vehicle-sales-secrets
                  key: ConnectionStrings__DefaultConnection

            - name: Authentication__Authority
              valueFrom:
                secretKeyRef:
                  name: vehicle-sales-secrets
                  key: Authentication__Authority

            - name: Authentication__Audience
              valueFrom:
                secretKeyRef:
                  name: vehicle-sales-secrets
                  key: Authentication__Audience