name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: VehicleSales

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore VehicleSales.sln

      - name: Build
        run: dotnet build VehicleSales.sln --no-restore

      - name: Test
        run: dotnet test VehicleSales.sln --no-build